### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by jkl1337** [fltk-rs/fltk-flow#2]
cfl_widget.hpp was moved to the source directory in more recent versions of cfltk so there is no way to instantiate the Widget_Derived template necessary for WIDGET_CLASS and WIDGET_DEFINE. If cfltk was meant to allow creation of custom wrappers that change totally broke it.

**Comment by MoAlyousef** [comment]
Thanks for the PR's. This will require a new version of fltk-sys at least which I'll update in a few days (unless you need it urgently).

**Comment by jkl1337** [comment]
No, not at all. Thanks for this.
